[custom]
;不要隨意改變關鍵字，否則會導致出錯
;acl4SSR規則-在線更新版

;去廣告：支持
;自動測速：支持
;微軟分流：支持
;蘋果分流：支持
;增強中國IP段：不支持
;增強國外GFW：不支持
;多國家分組：支持港/日/美

ruleset=🎯 全球直連,https://raw.githubusercontent.com/cmliu/ACL4SSR/refs/heads/main/Clash/CFnat.list
ruleset=🎯 全球直連,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直連,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 全球攔截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 應用凈化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🍃 應用凈化,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/adobe.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🎯 全球直連,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直連,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=Ⓜ️ 微軟服務,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 蘋果服務,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 電報信息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/juewuy/ShellClash/master/rules/ai.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Copilot.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/GithubCopilot.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Claude.list
ruleset=📹 油管視頻,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎥 奈飛視頻,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🌍 國外媒體,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🌍 國外媒體,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Emby.list
ruleset=🚀 節點選擇,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🚀 節點選擇,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/CMBlog.list
ruleset=🎯 全球直連,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直連,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
;ruleset=🎯 全球直連,[]GEOIP,LAN
ruleset=🎯 全球直連,[]GEOIP,CN
ruleset=🐟 漏網之魚,[]FINAL

custom_proxy_group=🚀 節點選擇`select`[]♻️ 自動選擇`[]🇯🇵 日本節點`[]🇭🇰 香港節點`[]🇺🇲 美國節點`[]☑️ 手動切換`[]DIRECT
custom_proxy_group=☑️ 手動切換`select`.*
custom_proxy_group=♻️ 自動選擇`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=📹 油管視頻`select`[]🚀 節點選擇`[]♻️ 自動選擇`[]☑️ 手動切換`[]DIRECT
custom_proxy_group=🎥 奈飛視頻`select`[]🚀 節點選擇`[]♻️ 自動選擇`[]☑️ 手動切換`[]DIRECT`(NF|奈飛|解鎖|Netflix|NETFLIX|Media|MITM)
custom_proxy_group=🌍 國外媒體`select`[]🚀 節點選擇`[]♻️ 自動選擇`[]🎯 全球直連`.*
custom_proxy_group=📲 電報信息`select`[]🚀 節點選擇`[]🎯 全球直連`.*
custom_proxy_group=🤖 OpenAi`select`[]🚀 節點選擇`[]♻️ 自動選擇`[]🇺🇲 美國節點`[]☑️ 手動切換`[]DIRECT
custom_proxy_group=Ⓜ️ 微軟服務`select`[]🎯 全球直連`[]🚀 節點選擇`.*
custom_proxy_group=🍎 蘋果服務`select`[]🚀 節點選擇`[]🎯 全球直連`.*
custom_proxy_group=📢 谷歌FCM`select`[]🚀 節點選擇`[]🎯 全球直連`[]♻️ 自動選擇`.*
custom_proxy_group=🎯 全球直連`select`[]DIRECT`[]🚀 節點選擇`[]♻️ 自動選擇
custom_proxy_group=🛑 全球攔截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 應用凈化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏網之魚`select`[]🚀 節點選擇`[]🎯 全球直連`[]♻️ 自動選擇`.*
custom_proxy_group=🇭🇰 香港節點`load-balance`(港|HK|hk|Hong Kong|HongKong|hongkong|HKG)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本節點`load-balance`(日本|川日|東京|大阪|泉日|埼玉|滬日|深日|[^-]日|JP|MY|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美國節點`load-balance`(美|波特蘭|達拉斯|俄勒岡|鳳凰城|費利蒙|矽谷|拉斯維加斯|洛杉磯|聖何塞|聖克拉拉|西雅圖|芝加哥|US|United States|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC)`http://www.gstatic.com/generate_204`300,,150



enable_rule_generator=true
overwrite_original_rules=true
